import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Jose Rojas Web Developer',
	description: 'Generated by create next app'
}

export default function LocaleLayout({
	children,
	params: { locale }
}: {
	children: React.ReactNode
	params: { locale: string }
}) {
	return (
		<html lang={locale}>
			<body className={inter.className}>{children}</body>
		</html>
	)
}

// export default function RootLayout({
// 	children
// }: Readonly<{
// 	children: React.ReactNode
// }>) {
// 	return (
// 		<html lang='en'>
// 			<body className={inter.className}>{children}</body>
// 		</html>
// 	)
// }
